### ISSUE TITLE
migration前にサービスに接続しようとするとエラーになる

### ISSUE THREAD

**Issue by naopr** [katakyo/PerfectRubyonRails#1]
READMEでは `docker-compose run app rails db:create` した直後にサービスに接続する手順になっていますが、そうするとmigration完了してませんよ的なエラーが出ました。

`rails db:migrate` を実行した後にはこのエラーが出なかったので、サービスに接続する手順をmigration後にしたほうがよかったりするでしょうか？もしくは、このエラーは自分の環境だけの問題でしょうか。

**Comment by katakyo** [comment]
おっしゃる通りで、サービスに接続する手順をmigration後にした方が良いです！
README.mdを修正しておきます！

**Comment by katakyo** [comment]
対応しました！
